config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user/show', to: "user#show"
  get 'list/show', to: 'list#show'
  get 'user/show/:id', to: 'user#search'
  get 'user/index', to: 'user#index'
  devise_scope :user do
    authenticated :user do
      root 'user#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_and_belongs_to_many :users
    belongs_to :user
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :lists
  has_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  def self.search(search)
    where("email ILIKE ? ", "%#{search}%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_controller.rb
class ListController < ApplicationController
    def show
        @user = current_user
        @lists = @user.lists.paginate(page: params[:page])
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end
  
  def search
    @user = User.find(params[:id])
    @lists = @user.lists.paginate(page: params[:page])
  end
  
  
  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all.order("created_at DESC")
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Mini-App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    
    <% if user_signed_in? %>
      <strong>Logado como <%= current_user.email %></strong>.
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% end %>
    
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if user_signed_in? %>
        <%= link_to "mini app", user_show_path, id: "logo" %>
    <% else %>
        <%= link_to "mini app", new_user_registration_path , id: "logo" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  
  
<%= yield %>
  <%= render 'layouts/footer' %>
  
</body>
</html>

app/views/list/show.html.erb
<% provide(:title, "Listas") %>


<h1>Todas as suas listas</h1>

<% x = 0 %>
<%@lists.each do |l| %>
    <h1>Lista: <%= l.name %></h1> <br/>
    <% l.tasks.each do |t| %>
        <h2><%= t.content %></h2>
    <%end%>
<%end%>

app/views/user/index.html.erb
<%= @user.email %>

app/views/user/search.html.erb
<h1>Usuário: <%= @user.email  %> </h1>

<%@lists.each do |l| %>
    <h1>Lista: <%= l.name %></h1> <br/>
    <% l.tasks.each do |t| %>
        <h2><%= t.content %></h2>
    <%end%>
<%end%>

app/views/user/show.html.erb
<% provide(:title, "Home") %>

<h1>Seja bem-vindo</h1>


<h2><%= link_to "Veja suas listas", list_show_path %></h2>


<h2><%= link_to "Veja listas de outro usuário", 'show/1' %></h2>


<%= form_tag(user_index_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Pesquise por usuários" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>